app = "vzenroom-server"

[build]
  image = "python:3.12-slim"

[env]
  PORT = "5000"
  HOST = "0.0.0.0"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
